// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE_IhAlm1YuQfaT2mLHFVjvB6DVEnDYrA',
    appId: '1:943749489398:web:378068be2c2358ec2242d7',
    messagingSenderId: '943749489398',
    projectId: 'project-3450519755386202855',
    authDomain: 'project-3450519755386202855.firebaseapp.com',
    storageBucket: 'project-3450519755386202855.appspot.com',
    measurementId: 'G-0E2TNVJ30H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWE2roo28zMANMXxQNkZP4es13mqH_2b0',
    appId: '1:943749489398:android:33a4f7d8fd08c6012242d7',
    messagingSenderId: '943749489398',
    projectId: 'project-3450519755386202855',
    storageBucket: 'project-3450519755386202855.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmY4DjKjvnW0ustL56d-j4fH9KMy4Uvac',
    appId: '1:943749489398:ios:2d67e46d6ebd095d2242d7',
    messagingSenderId: '943749489398',
    projectId: 'project-3450519755386202855',
    storageBucket: 'project-3450519755386202855.appspot.com',
    iosBundleId: 'com.example.flutterTrial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmY4DjKjvnW0ustL56d-j4fH9KMy4Uvac',
    appId: '1:943749489398:ios:2d67e46d6ebd095d2242d7',
    messagingSenderId: '943749489398',
    projectId: 'project-3450519755386202855',
    storageBucket: 'project-3450519755386202855.appspot.com',
    iosBundleId: 'com.example.flutterTrial',
  );
}
